services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: task_fella
    volumes:
      - task-fella-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d task_fella"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5432

volumes:
  task-fella-db:
    driver: local
